### Crear usuario
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "username": "juanperez",
  "email": "juan@email.com",
  "password": "Password123",
  "profile": {
    "firstName": "Juan",
    "lastName": "Pérez",
    "biography": "Desarrollador fullstack con 5 años de experiencia"
  }
}

### Traer Todos los Usuarios
GET http://localhost:4000/api/users
Content-Type: application/json

### Traer Usuarios por ID
GET http://localhost:4000/api/users/68d2a3e9e12da6b68506ebc0
Content-Type: application/json