### Crear usuario
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "username": "juanperez",
  "email": "juan@email.com",
  "password": "Password123",
  "profile": {
    "firstName": "Juan",
    "lastName": "Pérez",
    "biography": "Desarrollador fullstack con 5 años de experiencia"
  }
}

### Traer Todos los Usuarios
GET http://localhost:4000/api/users
Content-Type: application/json

### Traer Usuarios por ID
GET http://localhost:4000/api/users/68d2aaf680469086d10d646c
Content-Type: application/json

### Actualizar un usuario
PUT http://localhost:4000/api/users/68d2e4181e0e04aea3a67ca3
Content-Type: application/json

{
  "username": "juanperezactualizado",
  "email": "actualizadojuan@email.com",
  "password": "Password123aztualizado"
}

### Peticion para borrar un usuario
DELETE http://localhost:4000/api/users/68d2aaf680469086d10d646c
Content-Type: application/json




########## PETICIONES DE ARTICULOS ###########
POST http://localhost:4000/api/articles
Content-Type: application/json

{
  "title": "Articulo de Juan", 
  "content": "Mis proyectos de la tecnicatura superior de desarrollo de software del instituto", 
  "excerpt": "Trabajos", 
  "status": "published",
  "author": "68d2e4181e0e04aea3a67ca3",
  "tags":[]
}

##### Traer TODO LOS ARTICULOS
GET http://localhost:4000/api/articles
Content-Type: application/json

######## Traer UN ARTICULO POR ID
GET http://localhost:4000/api/articles/68d2b0a76c0c0c838939b78c
Content-Type: application/json

############ Actualizar un ARTICULO
PUT http://localhost:4000/api/articles/68d2b9e79cb7f28c599a54c6
Content-Type: application/json

{
  "title": "Articulo de Juan ACTUALIZADO", 
  "content": "Mis proyectos de la tecnicatura superior de desarrollo de software del instituto Y ESTO ESTA ACTUALIZADO", 
  "excerpt": "Trabajos Y ACTUALIZADO", 
  "status": "published"
}

########## Peticion para BORRAR UN ARTICULO
DELETE http://localhost:4000/api/articles/68d2b9e79cb7f28c599a54c6
Content-Type: application/json


######### Peticion para Crear una TAG
POST http://localhost:4000/api/tags/
Content-Type: application/json

# {
#   "name": "Programacion",
#   "description": "Todo lo relacionado a programacion",
#   "article": "68d2e4722980d8ae0fc4a15b" 
# }

# {
#   "name": "Cocina",
#   "description": "Todo lo relacionado a cocinar",
#   "article": "68d2e4722980d8ae0fc4a15b" 
# }

# {
#   "name": "Conduccion",
#   "description": "Todo lo relacionado a como manejar vehiculos",
#   "article": "68d2c5230f90e2c4205ef71a" 
# }

##### PETICION PARA TRAER TODAS LAS TAGS
GET http://localhost:4000/api/tags
Content-Type: application/json


### PETICION PARA TRAER UNA TAG POR ID
GET http://localhost:4000/api/tags/68d2c5360f90e2c4205ef71c
Content-Type: application/json

#### peticion para actualizar una tag
PUT http://localhost:4000/api/tags/68d2c5360f90e2c4205ef71c
Content-Type: application/json

{
  "name": "Programacion ACTUALIZADO",
  "description": "Todo lo relacionado a programacion ACTUALIZADO",
  "article": "68d2c5230f90e2c4205ef71a" 
}

#### Peticion para borrar una tag
DELETE http://localhost:4000/api/tags/68d2c5360f90e2c4205ef71c
Content-Type: application/json


#####  RUTAS DE COMMENTS
#### CREAR UN COMMENT
POST http://localhost:4000/api/comments
Content-Type: application/json

{
  "content": "Este es un comentario de prueba",
  "author": "68d2e4181e0e04aea3a67ca3",
  "article": "68d2e4722980d8ae0fc4a15b",
}